
apiVersion: batch/v1
kind: Job
metadata:
  name: print-task
  namespace: nginx  
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: demo-job-task
      labels:
        app: batch-task
    spec:
      containers:
      - name: batch-container
        image: busybox:latest
        command: ["sh",  "-c", "echo Hello!!!dosto; sleep 10" ]
      restartPolicy: Never
