apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replica-sets
  namespace: nginx    
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-rep-pod
  template:
    metadata:
      labels:
        app: nginx-rep-pod
    spec: 
      containers:
      - name: nginx-cont
        image: nginx:latest
        ports:
        - containerPort: 80
      
  
  
